spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  cache:
    cache-names: news
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: m2sm2sm2s@
    url: jdbc:mysql://114.67.75.238/m2s_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&useTimezone=true&allowPublicKeyRetrieval=true
  ai:
    openai:
      base-url: https://api.deepseek.com
      base-url2: https://api.chatanywhere.tech
      api-key: sk-dc03fa49759b4356ba29a2bab0c6a62c
      api-key2: sk-28noKxU9Jlto1PAtLkPRRZO7pS3LW78bYq2ivmc1DxWy2qoN
      chat:
        options:
          model: deepseek-chat
          model2: o3

# 日志配置，可以打印es的qsl语句
logging:
  level:
    tracer: trace


bailian:
  apiKey: sk-cb80f6a73a5f4ffb80b12f3260eb7217
  appId: 3612d3d43acf4b77b695c0859d7a1da9

bos:
  ak: 9c0ec7a5324645e89c98e8640536c1e6
  sk: 7832d71f382441e2afe8eccec6215e07
  endpoint: gz.bcebos.com
  bucketName: map-question


volcengine:
  apiKey: 1738aee7-8537-4266-9c79-c76afe147097

# mybatis日志打印
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

